name: lint,test,build
on: 
  issues:
    types: [opened,edited]
jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Show metadata
        run: ${{ github }}
