name: Show metadata
on: 
  issues:
    types: [opened,edited]
jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Show metadata
        run: echo "${{ toJSON(github) }}"
